-- Add extended patient profile fields and verification status
-- psql -d ids_clinic -f src/db/migrations/002_add_patient_extended_fields.sql

ALTER TABLE patients
  ADD COLUMN IF NOT EXISTS telefon VARCHAR(20),
  ADD COLUMN IF NOT EXISTS mobil VARCHAR(20),
  ADD COLUMN IF NOT EXISTS email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS domiciliu_tara VARCHAR(100),
  ADD COLUMN IF NOT EXISTS domiciliu_judet VARCHAR(100),
  ADD COLUMN IF NOT EXISTS domiciliu_localitate VARCHAR(120),
  ADD COLUMN IF NOT EXISTS domiciliu_adresa VARCHAR(200),
  ADD COLUMN IF NOT EXISTS domiciliu_numar VARCHAR(20),
  ADD COLUMN IF NOT EXISTS domiciliu_bloc VARCHAR(20),
  ADD COLUMN IF NOT EXISTS domiciliu_scara VARCHAR(20),
  ADD COLUMN IF NOT EXISTS domiciliu_etaj VARCHAR(20),
  ADD COLUMN IF NOT EXISTS domiciliu_apartament VARCHAR(20),
  ADD COLUMN IF NOT EXISTS resedinta_tara VARCHAR(100),
  ADD COLUMN IF NOT EXISTS resedinta_judet VARCHAR(100),
  ADD COLUMN IF NOT EXISTS resedinta_localitate VARCHAR(120),
  ADD COLUMN IF NOT EXISTS resedinta_adresa VARCHAR(200),
  ADD COLUMN IF NOT EXISTS resedinta_numar VARCHAR(20),
  ADD COLUMN IF NOT EXISTS resedinta_bloc VARCHAR(20),
  ADD COLUMN IF NOT EXISTS resedinta_scara VARCHAR(20),
  ADD COLUMN IF NOT EXISTS resedinta_etaj VARCHAR(20),
  ADD COLUMN IF NOT EXISTS resedinta_apartament VARCHAR(20),
  ADD COLUMN IF NOT EXISTS contact_nume VARCHAR(100),
  ADD COLUMN IF NOT EXISTS contact_prenume VARCHAR(100),
  ADD COLUMN IF NOT EXISTS contact_telefon VARCHAR(20),
  ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS contact_relatie VARCHAR(100),
  ADD COLUMN IF NOT EXISTS medic_familie_nume VARCHAR(150),
  ADD COLUMN IF NOT EXISTS medic_familie_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS nivel_notificari VARCHAR(100),
  ADD COLUMN IF NOT EXISTS sursa_informare VARCHAR(100),
  ADD COLUMN IF NOT EXISTS cas_status_asigurare VARCHAR(100),
  ADD COLUMN IF NOT EXISTS cas_denumire VARCHAR(120),
  ADD COLUMN IF NOT EXISTS cas_tip_asigurare VARCHAR(100),
  ADD COLUMN IF NOT EXISTS cas_nr_card_european VARCHAR(50),
  ADD COLUMN IF NOT EXISTS cas_card_valabil_pana DATE,
  ADD COLUMN IF NOT EXISTS cas_eminent VARCHAR(50),
  ADD COLUMN IF NOT EXISTS cas_cod_eminent VARCHAR(50),
  ADD COLUMN IF NOT EXISTS cas_categorie_asigurat TEXT,
  ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT FALSE;
