import { z } from 'zod'

const dateString = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Must be a date in YYYY-MM-DD format')
const medicalLetterSortKeySchema = z.enum([
  'date',
  'patient',
  'nid',
  'validationDoctor',
  'currentDoctor',
  'diagnosis',
  'validationTime',
  'sendStatus',
  'updateStatus',
  'isValid',
])

export const createMedicalLetterSchema = z.object({
  patientId: z.string().uuid(),
  patientName: z.string().min(1).max(201).default(''),
  patientNid: z.string().max(50).default(''),
  doctorId: z.string().uuid(),
  doctorName: z.string().max(200).default(''),
  letterDate: dateString,
  birthDate: dateString.nullable().optional(),
  patientAge: z.number().int().min(0).max(150).nullable().optional(),
  consultType: z.string().max(100).nullable().optional(),
  consultationReason: z.string().nullable().optional(),
  medicalHistory: z.string().nullable().optional(),
  firstHistoCito: z.string().nullable().optional(),
  firstHistoCitoDate: dateString.nullable().optional(),
  diagnosis: z.string().nullable().optional(),
  staging: z.string().max(50).nullable().optional(),
  stagingT: z.string().max(20).nullable().optional(),
  stagingN: z.string().max(20).nullable().optional(),
  stagingM: z.string().max(20).nullable().optional(),
  stage: z.string().max(20).nullable().optional(),
  icdCode: z.string().max(20).nullable().optional(),
  icdLocalization: z.string().max(100).nullable().optional(),
  ecog: z.number().int().min(0).max(5).nullable().optional(),
  examFieldsJson: z.record(z.unknown()).nullable().optional(),
  objectiveExamNotes: z.string().nullable().optional(),
  clinicalImagingBiochemistry: z.string().nullable().optional(),
  painIntensity: z.number().int().min(0).max(10).nullable().optional(),
  painLocalization: z.string().nullable().optional(),
  analgesicMedication: z.string().nullable().optional(),
  analgesicAdverseEffects: z.string().nullable().optional(),
  dyspneaIntensity: z.number().int().min(0).max(10).nullable().optional(),
  dyspneaTreatment: z.string().nullable().optional(),
  interactionsChecked: z.boolean().nullable().optional(),
  treatmentGoal: z.string().nullable().optional(),
  therapeuticConduct: z.string().nullable().optional(),
  treatmentPlan: z.string().nullable().optional(),
  adverseReactionsJson: z.record(z.unknown()).nullable().optional(),
  adverseReactionsNotes: z.string().nullable().optional(),
  nextAppointmentDate: dateString.nullable().optional(),
  periodicControlInterval: z.string().max(100).nullable().optional(),
  periodicControlNotes: z.string().nullable().optional(),
  lifestyleRecommendations: z.string().nullable().optional(),
  otherRecommendedInvestigations: z.string().nullable().optional(),
  geneticCounseling: z.string().nullable().optional(),
  otherRecommendations: z.string().nullable().optional(),
  icdIndication: z.string().nullable().optional(),
  returnAdmission: z.boolean().nullable().optional(),
  returnAdmissionDays: z.number().int().min(0).nullable().optional(),
  prescriptionStatus: z.boolean().nullable().optional(),
  prescriptionSeries: z.string().max(20).nullable().optional(),
  prescriptionNumber: z.string().max(50).nullable().optional(),
  medicalLeaveStatus: z.boolean().nullable().optional(),
  medicalLeaveSeries: z.string().max(20).nullable().optional(),
  medicalLeaveNumber: z.string().max(50).nullable().optional(),
  homeCareRecommendation: z.string().nullable().optional(),
  medicalDevicesPrescription: z.string().nullable().optional(),
  transmissionMode: z.string().max(100).nullable().optional(),
  documentS3Key: z.string().nullable().optional(),
  documentUrl: z.string().nullable().optional(),
  mediaItemId: z.string().uuid().nullable().optional(),
  createdByUserId: z.string().uuid(),
})

export const updateMedicalLetterSchema = z.object({
  patientName: z.string().min(1).max(201).optional(),
  patientNid: z.string().max(50).optional(),
  doctorId: z.string().uuid().optional(),
  doctorName: z.string().max(200).optional(),
  letterDate: dateString.optional(),
  birthDate: dateString.nullable().optional(),
  patientAge: z.number().int().min(0).max(150).nullable().optional(),
  consultType: z.string().max(100).nullable().optional(),
  consultationReason: z.string().nullable().optional(),
  medicalHistory: z.string().nullable().optional(),
  firstHistoCito: z.string().nullable().optional(),
  firstHistoCitoDate: dateString.nullable().optional(),
  diagnosis: z.string().nullable().optional(),
  staging: z.string().max(50).nullable().optional(),
  stagingT: z.string().max(20).nullable().optional(),
  stagingN: z.string().max(20).nullable().optional(),
  stagingM: z.string().max(20).nullable().optional(),
  stage: z.string().max(20).nullable().optional(),
  icdCode: z.string().max(20).nullable().optional(),
  icdLocalization: z.string().max(100).nullable().optional(),
  ecog: z.number().int().min(0).max(5).nullable().optional(),
  examFieldsJson: z.record(z.unknown()).nullable().optional(),
  objectiveExamNotes: z.string().nullable().optional(),
  clinicalImagingBiochemistry: z.string().nullable().optional(),
  painIntensity: z.number().int().min(0).max(10).nullable().optional(),
  painLocalization: z.string().nullable().optional(),
  analgesicMedication: z.string().nullable().optional(),
  analgesicAdverseEffects: z.string().nullable().optional(),
  dyspneaIntensity: z.number().int().min(0).max(10).nullable().optional(),
  dyspneaTreatment: z.string().nullable().optional(),
  interactionsChecked: z.boolean().nullable().optional(),
  treatmentGoal: z.string().nullable().optional(),
  therapeuticConduct: z.string().nullable().optional(),
  treatmentPlan: z.string().nullable().optional(),
  adverseReactionsJson: z.record(z.unknown()).nullable().optional(),
  adverseReactionsNotes: z.string().nullable().optional(),
  nextAppointmentDate: dateString.nullable().optional(),
  periodicControlInterval: z.string().max(100).nullable().optional(),
  periodicControlNotes: z.string().nullable().optional(),
  lifestyleRecommendations: z.string().nullable().optional(),
  otherRecommendedInvestigations: z.string().nullable().optional(),
  geneticCounseling: z.string().nullable().optional(),
  otherRecommendations: z.string().nullable().optional(),
  icdIndication: z.string().nullable().optional(),
  returnAdmission: z.boolean().nullable().optional(),
  returnAdmissionDays: z.number().int().min(0).nullable().optional(),
  prescriptionStatus: z.boolean().nullable().optional(),
  prescriptionSeries: z.string().max(20).nullable().optional(),
  prescriptionNumber: z.string().max(50).nullable().optional(),
  medicalLeaveStatus: z.boolean().nullable().optional(),
  medicalLeaveSeries: z.string().max(20).nullable().optional(),
  medicalLeaveNumber: z.string().max(50).nullable().optional(),
  homeCareRecommendation: z.string().nullable().optional(),
  medicalDevicesPrescription: z.string().nullable().optional(),
  transmissionMode: z.string().max(100).nullable().optional(),
  documentS3Key: z.string().nullable().optional(),
  documentUrl: z.string().nullable().optional(),
  mediaItemId: z.string().uuid().nullable().optional(),
  version: z.number().int().positive().optional(),
})

export const validateMedicalLetterSchema = z.object({
  validatedByUserId: z.string().uuid(),
  version: z.number().int().positive().optional(),
})

export const medicalLetterListQuerySchema = z.object({
  q: z.string().optional(),
  patientId: z.string().uuid().optional(),
  patientName: z.string().optional(),
  patientNid: z.string().optional(),
  nid: z.string().optional(),
  doctorId: z.string().uuid().optional(),
  doctorName: z.string().optional(),
  medicCurant: z.string().optional(),
  currentDoctor: z.string().optional(),
  validated: z.enum(['true', 'false']).optional(),
  letterDateFrom: dateString.optional(),
  letterDateTo: dateString.optional(),
  sortKey: medicalLetterSortKeySchema.optional(),
  sortDirection: z.enum(['asc', 'desc']).optional(),
  cursor: z.string().optional(),
  limit: z.string().optional(),
  includeTotal: z.enum(['true', 'false']).optional(),
})

export type CreateMedicalLetterInput = z.infer<typeof createMedicalLetterSchema>
export type UpdateMedicalLetterInput = z.infer<typeof updateMedicalLetterSchema>
export type ValidateMedicalLetterInput = z.infer<typeof validateMedicalLetterSchema>
export type MedicalLetterListQuery = z.infer<typeof medicalLetterListQuerySchema>
